all:
	pdflatex  texmex.tex
	bibtex  texmex
	pdflatex  texmex.tex
	pdflatex  texmex.tex
	rm *.log texmex.aux texmex.bbl texmex.blg texmex.tex
	
clean:
	rm *.log texmex.aux texmex.bbl texmex.blg texmex.tex
  
