// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// exprel
Rcpp::NumericVector exprel(const Rcpp::NumericVector& x);
RcppExport SEXP _texmex_exprel(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(exprel(x));
    return rcpp_result_gen;
END_RCPP
}
// log1prel
Rcpp::NumericVector log1prel(const Rcpp::NumericVector& x);
RcppExport SEXP _texmex_log1prel(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(log1prel(x));
    return rcpp_result_gen;
END_RCPP
}
// log1mexp
Rcpp::NumericVector log1mexp(const Rcpp::NumericVector& x);
RcppExport SEXP _texmex_log1mexp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(log1mexp(x));
    return rcpp_result_gen;
END_RCPP
}
// _safe_product
Rcpp::NumericVector _safe_product(const Rcpp::NumericVector& x, const Rcpp::NumericVector& y);
RcppExport SEXP _texmex__safe_product(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(_safe_product(x, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_texmex_exprel", (DL_FUNC) &_texmex_exprel, 1},
    {"_texmex_log1prel", (DL_FUNC) &_texmex_log1prel, 1},
    {"_texmex_log1mexp", (DL_FUNC) &_texmex_log1mexp, 1},
    {"_texmex__safe_product", (DL_FUNC) &_texmex__safe_product, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_texmex(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
