# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Accurately compute (exp(x) - 1) / x
#' @param x numeric vector
#' @return numeric vector
.exprel <- function(x) {
    .Call(`_texmex_exprel`, x)
}

#' Accurately compute log(1 + x) / x
#' @param x numeric vector
#' @return numeric vector
.log1prel <- function(x) {
    .Call(`_texmex_log1prel`, x)
}

#' Accurately compute log(1-exp(x))
#' @param x numeric vector
#' @return a numeric vector
.log1mexp <- function(x) {
    .Call(`_texmex_log1mexp`, x)
}

